const body = document.querySelector("body")
const main = document.createElement("main")
const div = document.createElement("div")
const name = document.createElement("input")
const surname = document.createElement("input")
const delivery_date =document.createElement("input")
const street =document.createElement("input")
const house_number =document.createElement("input")
const flat_number =document.createElement("input")
const radio_cash_box = document.createElement("div")
const radio_card_box = document.createElement("div")
const radio_cash_btn = document.createElement("input")
const radio_card_btn = document.createElement("input")
const radio_cash_label = document.createElement("label")
const radio_card_label = document.createElement("label")
const pack_gift_box = document.createElement("div")
const gift_pack_check = document.createElement("input")
const gift_pack_label = document.createElement("label")
const postcard_gift_box = document.createElement("div")
const gift_postcard_check = document.createElement("input")
const gift_postcard_label = document.createElement("label")
const discount_gift_box = document.createElement("div")
const gift_discount_check = document.createElement("input")
const gift_discount_label = document.createElement("label")
const branded_gift_box = document.createElement("div")
const gift_branded_check = document.createElement("input")
const gift_branded_label = document.createElement("label")
const submit = document.createElement("button")

body.classList.add("validation-body")
div.classList.add("validation-box")
name.classList.add("name")
surname.classList.add("surname")
delivery_date.classList.add("delivery-date")
street.classList.add("street")
house_number.classList.add("house-number")
flat_number.classList.add("flat-number")
radio_cash_btn.classList.add("radio-cash-btn")
radio_cash_label.classList.add("radio-cash-label")
radio_card_btn.classList.add("radio-card-btn")
radio_card_btn.classList.add("radio-card-label")
radio_cash_box.classList.add("radio-cash-box")
radio_card_box.classList.add("radio-card-box")
pack_gift_box.classList.add("check-gift-box")
gift_pack_check.classList.add("gift-pack-check")
gift_pack_label.classList.add("gift-pack-label")
postcard_gift_box.classList.add("postcard-gift-box")
gift_postcard_check.classList.add("gift-postcard-check")
gift_postcard_label.classList.add("gift-postcard-label")
discount_gift_box.classList.add("discount-gift-box")
gift_discount_check.classList.add("gift-discount-check")
gift_discount_label.classList.add("gift-discount-label")
branded_gift_box.classList.add("branded-gift-box")
gift_branded_check.classList.add("gift-branded-check")
gift_branded_label.classList.add("gift-branded-label")
submit.classList.add("submit")

name.setAttribute("type", "text")
surname.setAttribute("type", "text")
delivery_date.setAttribute("type","text")
street.setAttribute("type","text")
house_number.setAttribute("type","number")
flat_number.setAttribute("type","number")
radio_cash_btn.setAttribute("type","radio")
radio_cash_btn.setAttribute("value","cash")
radio_cash_btn.setAttribute("name","pay")
radio_cash_label.setAttribute("for","cash")
radio_card_btn.setAttribute("type","radio")
radio_card_btn.setAttribute("value","cash")
radio_card_btn.setAttribute("name","pay")
radio_card_label.setAttribute("for","cash")
gift_pack_check.setAttribute("type","checkbox")
gift_pack_check.setAttribute("name","gift")
gift_pack_label.setAttribute("for", "pack")
gift_postcard_check.setAttribute("type","checkbox")
gift_postcard_check.setAttribute("name","gift")
gift_postcard_label.setAttribute("for", "postcard")
gift_discount_check.setAttribute("type","checkbox")
gift_discount_check.setAttribute("name","gift")
gift_discount_label.setAttribute("for", "discount")
gift_branded_check.setAttribute("type","checkbox")
gift_branded_check.setAttribute("name","gift")
gift_branded_label.setAttribute("for", "branded")

radio_card_label.innerText = "payment type Card"
radio_cash_label.innerText = "payment type Cash"
gift_pack_label.innerText = "pack as a gift"
gift_postcard_label.innerText = "add postcard"
gift_discount_label.innerText = "provide 2% discount to the next time"
gift_branded_label.innerText = "branded pen or pencil"
submit.innerText = "Submit"

body.appendChild(main)
main.appendChild(div)
div.appendChild(name)
div.appendChild(surname)
div.appendChild(delivery_date)
div.appendChild(street)
div.appendChild(house_number)
div.appendChild(flat_number)
div.appendChild(radio_cash_box)
div.appendChild(radio_card_box)
radio_cash_box.appendChild(radio_cash_btn)
radio_cash_box.appendChild(radio_cash_label)
radio_card_box.appendChild(radio_card_btn)
radio_card_box.appendChild(radio_card_label)
div.appendChild(pack_gift_box)
pack_gift_box.appendChild(gift_pack_check)
pack_gift_box.appendChild(gift_pack_label)
div.appendChild(postcard_gift_box)
postcard_gift_box.appendChild(gift_postcard_check)
postcard_gift_box.appendChild(gift_postcard_label)
div.appendChild(discount_gift_box)
discount_gift_box.appendChild(gift_discount_check)
discount_gift_box.appendChild(gift_discount_label)
div.appendChild(branded_gift_box)
branded_gift_box.appendChild(gift_branded_check)
branded_gift_box.appendChild(gift_branded_label)
div.appendChild(submit)


